### ISSUE TITLE
Possible LS issue

### ISSUE THREAD

**Issue by mackness** [slomkowski/bash-full-of-colors#3]
This happened the first time I ran LS
```username:~ $ ls
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]

**Comment by slomkowski** [comment]
You seem to use some non-standard *ls* implementation. In this project, `ls` is an alias of `ls --color=auto -h`. You can edit *bash_aliases.sh*, line 3 and remove `--color=auto` option.
